### ISSUE TITLE
Word Fail

### ISSUE THREAD

**Issue by ghost** [hisbaan/didyoumean#21]
So I saw this, fought with my package manager (cue Karen joke fighting with the manager) to get it installed, first test fails.

So if it's not obvious I'm 12 (at hart <-- see what I did there?) I tested the with the word "fert." The expectation was the top match should be fart but fart is no where to be seen...or smelt...(again see what I did there? I've got a million of them I tellz ya!) Swing and a miss. Then I tried "hart", again expecting heart, swing and a miss. If it wasn't obvious "smelt" also failed to suggest smelled.

Is there a way to improve matching? So far it's failed every test word but one.

**Comment by hisbaan** [comment]
> So I saw this, fought with my package manager (cue Karen joke fighting with the manager) to get it installed, first test fails.

Which distro/OS are you using? I'd love to streamline the process for all sorts of systems! The built-in tests are running fine for me so I'm not sure exactly what you're referring to.

> Is there a way to improve matching? So far it's failed every test word but one.

Regarding the test words: unfortunately, due to the nature of how the app works, accurate matches on short words are not likely. This is because there are lots and lots of short words that are very similar to one another. 

When searching for `hart` (with the current word list, subject to change), `heart` still only has an edit distance of 1 but since there are so many words with an edit distance of 1, it comes 37th:

![image](https://user-images.githubusercontent.com/34548959/171088592-3d40596d-a4c8-4889-b26e-7289f9ee6175.png)

`smelt` and `smelled` are not similar in terms of spelling. They have an edit distance of 3 from one another (which is quite large in the realm of spelling corrections for short words):

![image](https://user-images.githubusercontent.com/34548959/171088757-822ab839-be07-4239-b1bf-4f6ff6883e0b.png)

The only thing I can think of that would make this better is sorting the word list based on probability of occurrence but I think that is more trouble than it's worth (especially since I now support 60 languages, I can't do that in all of them!). The reason I say that is this application is mostly for minor spelling corrections that you make when spelling complicated words, so short words don't really fall into the target usage so to speak. My success rate for longer words has been pretty good because there are fewer similar words to compare to the longer your test word gets.

Thank you for your contribution! Every little bit is appreciated :)

**Comment by ghost** [comment]
I'm on Arch/Garuda. I initially tried installing with pamac but it failed, so then I tried the git version via pamac, same same but I didn't really check the build scripts or anything. I then tried yaourt and it installed fine. One of the issues was I had rust installed but not through my package manager and so on top of the build failing it was also trying to install rust (which was already installed) heh.

There is a lot of "I plead ignorance" to this as I just saw a mention of this and thought hell that could be useful so I wanted to try it. i.e. I didn't look into how it's matching or anything else. Which is also to say length and per character are the base of the matching but it would really also need a system for phonetic matching. A small nightmare for one language never mind 60. Which is also to say my lord this could get complex hehe.

As for improving the matches it kinda sounds like on a simplistic level maybe an sqlite db to track user selections to rank a match in hopes if it's a word they always forget and look up eventually either the rank will ensure they get the right one over time or they will finally remember the correct spelling. I know there are some words that just never stick for spelling. They are used enough to be problematic but not enough to remember the damned spelling of.

This is also just as you said a probability indicator as most peoples vocabulary is basic in comparison to their language as a whole. If you can slowly reduce rank of really fringe words a user never uses you reduce the match list and hopefully the right stuff will creep up in rank. Though that's still a lot of work. I know I tried something similar a while back with a prediction system for my RSS system to help rank feed items in likelyhood of interest but yeah, simple but very not simple.

Thanks for replying.

**Comment by hisbaan** [comment]
I'll definitely try and improve it over time! Thanks for your feedback :)
