### ISSUE TITLE
Consider a different exit code and message when the input is spelled correctly

### ISSUE THREAD

**Issue by adam-gaia** [hisbaan/didyoumean#22]
I would really appreciate a different exit code when my input word is spelled correctly vs when it is not. 

Additionally, I would like to see a different message noting that my input was spelled correctly. Sometimes (when I forget to specify `-v`), I have to take a moment to double check if the first result is different from my input word.

```
$ dym supercalifragilisticexpialidocious # correct spelling
supercalifragilisticexpialidocious is spelled correctly
$ echo $?
0

$ dym supercalifragilisticexpialidociouX # last char typo
Did you mean?
1. supercalifragilisticexpialidocious
2. supercalifragilistic
3. superphlogistication
4. superartificiality
5. supercapabilities
$ echo $?
1
```

Regardless, thanks for your work on dym. It is very helpful as is!

**Comment by hisbaan** [comment]
Thank you for using dym! It's great to know people actually find it helpful :)

We can certainly add that functionality but I think printing out the list would still be a good idea since you can spell a word correctly and still want to get the other words. Something like:

```
$ dym x
x is spelled correctly

Did you mean:
1. x
2. y
3. z
...
```

I was also thinking about highlighting the matching entry in some color like orange or red. I was working on a feature to do diff-like highlighting on every word but the complexities and a lack of free time led to that going on the back burner. 

As for the exit code anything other than 0 typically indicates failure, I personally don't want to classify a valid result as a failure. The main reason is it would break many people's script integrations that expect a 0 exit code on success.

Let me know if you have any suggestions, otherwise I'll add the features we discussed here some time in the next few days
